"""initial migration

Revision ID: 34a70c1a2d8b
Revises: 
Create Date: 2022-06-16 10:44:10.639427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a70c1a2d8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banda', sa.String(length=64), nullable=True),
    sa.Column('responsavel', sa.String(length=64), nullable=True),
    sa.Column('dia', sa.Date(), nullable=True),
    sa.Column('horario', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_banda'), 'bookings', ['banda'], unique=True)
    op.create_index(op.f('ix_bookings_dia'), 'bookings', ['dia'], unique=True)
    op.create_index(op.f('ix_bookings_horario'), 'bookings', ['horario'], unique=True)
    op.create_index(op.f('ix_bookings_responsavel'), 'bookings', ['responsavel'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_responsavel'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_horario'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_dia'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_banda'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
