"""remove index

Revision ID: 822af2eecf55
Revises: 8a9383761ab3
Create Date: 2022-06-16 20:15:10.892115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822af2eecf55'
down_revision = '8a9383761ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_banda', table_name='bookings')
    op.drop_index('ix_bookings_dia', table_name='bookings')
    op.drop_index('ix_bookings_email', table_name='bookings')
    op.drop_index('ix_bookings_horario', table_name='bookings')
    op.drop_index('ix_bookings_responsavel', table_name='bookings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bookings_responsavel', 'bookings', ['responsavel'], unique=False)
    op.create_index('ix_bookings_horario', 'bookings', ['horario'], unique=False)
    op.create_index('ix_bookings_email', 'bookings', ['email'], unique=False)
    op.create_index('ix_bookings_dia', 'bookings', ['dia'], unique=False)
    op.create_index('ix_bookings_banda', 'bookings', ['banda'], unique=False)
    # ### end Alembic commands ###
