"""removendo unique

Revision ID: 8a9383761ab3
Revises: 646faff799d5
Create Date: 2022-06-16 20:11:11.527640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9383761ab3'
down_revision = '646faff799d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_banda', table_name='bookings')
    op.create_index(op.f('ix_bookings_banda'), 'bookings', ['banda'], unique=False)
    op.drop_index('ix_bookings_dia', table_name='bookings')
    op.create_index(op.f('ix_bookings_dia'), 'bookings', ['dia'], unique=False)
    op.drop_index('ix_bookings_email', table_name='bookings')
    op.create_index(op.f('ix_bookings_email'), 'bookings', ['email'], unique=False)
    op.drop_index('ix_bookings_horario', table_name='bookings')
    op.create_index(op.f('ix_bookings_horario'), 'bookings', ['horario'], unique=False)
    op.drop_index('ix_bookings_responsavel', table_name='bookings')
    op.create_index(op.f('ix_bookings_responsavel'), 'bookings', ['responsavel'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_responsavel'), table_name='bookings')
    op.create_index('ix_bookings_responsavel', 'bookings', ['responsavel'], unique=False)
    op.drop_index(op.f('ix_bookings_horario'), table_name='bookings')
    op.create_index('ix_bookings_horario', 'bookings', ['horario'], unique=False)
    op.drop_index(op.f('ix_bookings_email'), table_name='bookings')
    op.create_index('ix_bookings_email', 'bookings', ['email'], unique=False)
    op.drop_index(op.f('ix_bookings_dia'), table_name='bookings')
    op.create_index('ix_bookings_dia', 'bookings', ['dia'], unique=False)
    op.drop_index(op.f('ix_bookings_banda'), table_name='bookings')
    op.create_index('ix_bookings_banda', 'bookings', ['banda'], unique=False)
    # ### end Alembic commands ###
